[build]
  command = "npm run build:dist"
  publish = "dist"
  functions = "dist-serverless"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'https://storage.googleapis.com/workbox-cdn/*';
      object-src 'none' '''
